name: GitHub Pages
on:
  push:
    branches:
      - sphinx_test  # Set a branch name to trigger deployment
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      #- name: Install dependencies
      #    run: python3 -m pip install -r ./requirements.txt
      - name: Build HTML
          uses: ammaraskar/sphinx-action@0.4
      - name: Upload artifacts
          uses: actions/upload-artifact@v1
          with:
            name: html-docs
            path: build/html/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages